### ISSUE TITLE
Export more packages with bnd

### ISSUE THREAD

**Issue by balazs-zsoldos** [jsr107/jsr107spec#297] opened 2014-02-28 17:13 UTC
Currently only a few packages are exported. Infinispan misses the following additional packages:

 - javax.cache.configuration
 - javax.cache.expiry
 - javax.cache.integration
 - javax.cache.management
 - javax.cache.processor

It would be nice to add them to the Export-Package list in the bnd file. Or, if there is no private package (would be strange to have a private package in an API), it would be nice to add javax.cache.* to the Export-Package so all packages will be exported in the future automatically.

**Comment by rgilles** [comment] 2015-04-27 03:33
Hi,
Could you explain why this feature has been move to the 1.1?
I agree with you, it can be see as a new feature as it 'adds' new package to export section but I think for existing projects that are already implementing the 1.0.0 specification and their clients moving to 1.1 may require time but we need it on the 1.0 without waiting for the 1.1.

Regards,
Romain.

**Comment by gregrluck** [comment] 2015-04-27 16:53
Romain

"1.1' is simply the next release we are working on. It will either be called 1.0.1 or 1.1. We are calling it 1.1. for now. So it is the very next release of JCache. There is no quicker path.

**Comment by rgilles** [comment] 2015-04-30 09:09
Ok.
Thank you for the reply.
I don't know regarding the license if I can repackage the jcache-api and redistribute it under maven central with my gav=org.javabits.cache:cache-api:1.0.1 ?
What do you think?

If not I will leave with that ;)

Regards,
Romain.

**Comment by rgilles** [comment] 2015-04-30 09:12
I notice that you are not using maven to do the release if you want I can help you to setup maven in order to do the release with: 
```
> mvn release:prepare
> mvn release:perform
```
commands.

Romain

**Comment by gregrluck** [comment] 2015-10-10 23:01
I updated bnd.bnd to

Export-Package: javax.cache;\
	javax.cache.annotation;\
	javax.cache.configuration;\
	javax.cache.event;\
	javax.cache.expiry;\
	javax.cache.integration;\
	javax.cache.management;\
	javax.cache.processor;\
	javax.cache.spi;\
Bundle-SymbolicName: javax.cache
Bundle-Version: ${project.version}

But I don't see how we can change the 1.0.0 version up on Maven as it is a change. I have put this in the 1.1.0 version.

I also have a question about packageinfo. They all say 1.0 right now. Should they be changed to ${project.version} also?

**Comment by gregrluck** [comment] 2015-10-10 23:02
This is a duplicate of #326

**Closed by gregrluck** 2015-10-10 23:01 UTC
Labels: Feature Request
