### ISSUE TITLE
MutableConfiguration default constructor is wrong

### ISSUE THREAD

**Issue by alexsnaps** [jsr107/jsr107spec#301] opened 2014-10-01 01:59 UTC
Quickly reviewing the `MutableConfiguration` I was surprised by the two lines at
https://github.com/jsr107/jsr107spec/blob/master/src/main/java/javax/cache/configuration/MutableConfiguration.java#L107

I'm fairly confident this is wrong, not necessarily a huge deal, but this simple code
```
MutableConfiguration<String, String> configuration = new MutableConfiguration<String, String>();
Class<String> keyType = configuration.getKeyType();
String s = keyType.newInstance();
```
This last line would throw a `java.lang.ClassCastException` because `java.lang.Object` cannot be cast to `java.lang.String` as the `javax.cache.configuration.MutableConfiguration#keyType` is actually `Class<Object>`. This can be worked around by invoking `javax.cache.configuration.MutableConfiguration#setTypes` explicitly like so

```
MutableConfiguration<String, String> configuration = new MutableConfiguration<String, String>().setTypes(String.class, String.class);
Class<String> keyType = configuration.getKeyType();
String s = keyType.newInstance();
```

But this remains unfortunate. Also remains a problem for implementors that want to record the actual type, as any `Cache` created using a `Configuration` instantiated by this constructor and not having the `MutableConfiguration#setTypes` invoked will effectively be a `Cache<Object, Object>`, i.e. accepting any type.

**Comment by gregrluck** [comment] 2015-10-10 23:03
Any update on this. Working on 1.1 now.

**Comment by cruftex** [comment] 2016-03-10 18:58
The catch 22 is that `Object.class` is the defined value for *undefined* in the `Configuration`:

````
  /**
   * Determines the required type of keys for {@link Cache}s configured
   * with this {@link Configuration}.
   *
   * @return the key type or <code>Object.class</code> if the type is undefined
   */
  Class<K> getKeyType();
````


If *undefined* is defined as null, you could just remove the two lines from the default constructor:

````
    this.keyType = (Class<K>)Object.class;
    this.valueType = (Class<V>)Object.class;
````

Don't those casts look suspicious?

You could remove the lines and provide another constructor with the two types. That may break at some places but it would be quite obvious. But nice, it is not.

**Comment by cruftex** [comment] 2016-03-10 19:06
Correction: Adding a constructor is not strictly API compatible. `MutableConfiguration` isn't final and therefore open for subclassing. Adding a factory method will work.

**Comment by cruftex** [comment] 2016-03-11 11:06
I investigated the TCK code. Altogether there are 131 of the default constructor. Changing something here will impact existing applications and implementations, that's probably not worth the effort and would be too surprising for a MR.

**Comment by gregrluck** [comment] 2016-05-14 09:48
I think we agreed here we are not fixing. Maybe that is a forlorn hope. Going to close this.

**Comment by ljacomet** [comment] 2016-05-14 17:36
Could we not at least:
* Add another constructor that takes the key and value types as parameter
* Deprecate the existing no-arg constructor

While not ideal, these changes would improve the situation.

**Comment by cruftex** [comment] 2016-05-15 06:43
Agree, if we can improve a little its better then nothing.

@ljacomet Can you please help and make a specific proposal?

**Comment by ljacomet** [comment] 2016-05-15 09:25
Sure:

```
diff --git i/src/main/java/javax/cache/configuration/MutableConfiguration.java w/src/main/java/javax/cache/configuration/MutableConfiguration.java
index d7d5521..040cc8b 100644
--- i/src/main/java/javax/cache/configuration/MutableConfiguration.java
+++ w/src/main/java/javax/cache/configuration/MutableConfiguration.java
@@ -128,10 +128,23 @@ public class MutableConfiguration<K, V> implements CompleteConfiguration<K, V> {
 
   /**
    * Constructs a default {@link MutableConfiguration}.
+   *
+   * @deprecated Use the constructor taking the key and value type as parameters
    */
+  @Deprecated
   public MutableConfiguration() {
-    this.keyType = (Class<K>)Object.class;
-    this.valueType = (Class<V>)Object.class;
+    this((Class) Object.class, (Class) Object.class);
+  }
+
+  /**
+   * Constructs a {@code MutableConfiguration} with the given key and value types.
+   *
+   * @param keyType the key type
+   * @param valueType the value type
+   */
+  public MutableConfiguration(Class<K> keyType, Class<V> valueType) {
+    this.keyType = keyType;
+    this.valueType = valueType;
     this.listenerConfigurations = new
         HashSet<CacheEntryListenerConfiguration<K, V>>();
     this.cacheLoaderFactory = null;
```

**Comment by cruftex** [comment] 2016-05-16 07:28
Ahh. Code is always easier to read and natural language that describe what changes need to be done...

Deprecation:

It is basically (not strictly) a bean. Beans have a default constructor.

The usage pattern of a bean is by setting its properties via the setters/getters. This won't change.
So when you deprecate the default constructor you make everybody to change its code from
`new MutableConfiguratoin()` to `new MutableConfiguratoin(Object.class, Object.class)`. Including the 131 occurrences in the TCK.

We will never really take it away, will we?

**Comment by cruftex** [comment] 2016-05-16 07:47
After giving this more thought, I came to this conclusion:

We should only improve the Java Doc of the default constructor, but not change any code.

The usage pattern now, with specified types, is:

````
  new MutableConfiguratoin()
    .setTypes(Integer.class, String.class)
    .setReadThrough(true)
 . . .
````

After adding the second constructor this example has two variations. The one as shown above, and the new one using the 2-arg constructor.

Which is the preferred one? Do all examples, all documentation that is out, need to change?
Furthermore, new applications, new examples, new documentation may not be compatible to 1.0, because of this.

**Comment by cruftex** [comment] 2016-06-06 14:54
Created PR that improves the constructor doc.

**Comment by gregrluck** [comment] 2016-10-02 20:14
Took the suggestion from @cruftex to add JavaDoc. Also added a new constructor which takes the types.

**Comment by gregrluck** [comment] 2016-10-02 20:15
Clarified JavaDoc over the behaviour of type erasure with the default MutableConfiguration() constructor. Added a constructor which takes the key and value types for a minimal constructor with type enforcement.

**Comment by cruftex** [comment] 2016-10-05 18:22
The commit 18e7fc3:

````
  public MutableConfiguration(Class<K> keyType, Class<V> valueType) {
     this();
     this.keyType = (Class<K>)keyType;
     this.valueType = (Class<V>)valueType;
   }
````

- null-checks are missing. This is not in lieu with the rest of the code.
- Are there TCK tests for this new configuration variation?
- I thought hard about this, and I think I made a profound reasoning above, why not to add it. Why add it?

**Comment by gregrluck** [comment] 2016-10-05 22:49
I am not hard on the idea of adding it. We can 
Regards

Greg Luck

web: http://gregluck.com <http://gregluck.com/>
skype: gregrluck
mobile US: +1 650 924 6244
mobile Australia: +61 408 061 622

**Comment by alexsnaps** [comment] 2016-10-13 13:30
Deprecating still has its merit:
```
MutableConfiguration<String, String> configuration = new MutableConfiguration<>();
Class<String> keyType = configuration.getKeyType();
String s = keyType.newInstance(); // BOOM
```
If it'd be deprecated, I'd at least be warned that I'm doing something wrong... and would have an alternative to get back onto "type-safe-land"... I understand the example above is probably not some code that someone would write easily, but there are more issues with regards to type safety with this current bug: e.g. type enforcement on persistent or distributed caches on restarts or disjoint configs across nodes...

**Comment by cruftex** [comment] 2016-10-13 15:09
> If it'd be deprecated, I'd at least be warned that I'm doing something wrong...

The problem is, that this constructor is exactly the one being in use now. So there will be 99,9% correct applications get a warning, too and need to do a useless change. In terms of API design, I am with you, this could be improved. But sadly, it is shipped already.

I doubt that so much users run into this pitfall since the examples/tutorials show how to use it.
@alexsnaps , @ljacomet : Can you cite/refer users having problems here?

> ...but there are more issues with regards to type safety with this current bug: e.g. type enforcement on persistent or distributed caches on restarts or disjoint configs across nodes...

At least, your example above crashes early!

**Comment by alexsnaps** [comment] 2016-10-21 14:23
As I said it in the past, (almost 2 years now!) https://github.com/jsr107/jsr107spec/issues/301#issuecomment-66802989 I don't see how to address this cleanly... as you just said: it shipped. Maybe deprecating it is the way to go, but "only" as part of a 2.0?

**Comment by gregrluck** [comment] 2016-10-24 01:34
Putting it back the way it was. Lets take another look in JCache 2.0.

A comment was made further back that a no-arg Constructor was needed for Serialization. Not so according to http://www.jguru.com/faq/view.jsp?EID=251942.

The semantics of calling the default constructor are that runtime type enforcement is not enabled for the cache. Nor are any other configuration properties set. The whole constructor API is designed to be used in the fluent style. So I think this whole thread might be a little overblown.

**Closed** 2016-10-24 01:34 UTC
Labels: Clarification, PR-Pending
